#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Feb 26, 2025 10:47:33 AM PST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 438x450+702+270
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1920 1060
    wm minsize $top 438 450
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    frame "$top.fra47" \
        -borderwidth 2 -relief groove -background #d9d9d9 -height 435 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 420 
    vTcl:DefineAlias "$top.fra47" "F_install" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra47
    label "$site_3_0.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Installing Languages" 
    vTcl:DefineAlias "$site_3_0.lab47" "L_installTitle" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab48" \
        -activebackground #d9d9d9 -activeforeground black -anchor e \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12 -slant italic" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Installing..." 
    vTcl:DefineAlias "$site_3_0.lab48" "L_installStatus" vTcl:WidgetProc "Toplevel1" 1
    frame "$site_3_0.fra48" \
        -borderwidth 2 -relief groove -background #d9d9d9 -height 315 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 385 
    vTcl:DefineAlias "$site_3_0.fra48" "F_outputText" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra48
    vTcl::widgets::ttk::custom::CreateCmd "$site_4_0.cus49" \
        -background #d9d9d9 -height 319 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -width 384 
    vTcl:DefineAlias "$site_4_0.cus49" "C_outputTextScrolled" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.cus49 \
        -in $site_4_0 -x 0 -y 0 -width 0 -relwidth 0.997 -height 0 \
        -relheight 1.013 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.024 -y 0 -rely 0.014 -width 0 \
        -relwidth 0.319 -height 0 -relheight 0.049 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.357 -y 0 -rely 0.88 -width 0 \
        -relwidth 0.605 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra48 \
        -in $site_3_0 -x 0 -relx 0.043 -y 0 -rely 0.093 -width 0 \
        -relwidth 0.917 -height 0 -relheight 0.729 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra47 \
        -in $top -x 0 -relx 0.023 -y 0 -rely 0.022 -width 0 -relwidth 0.959 \
        -height 0 -relheight 0.96 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

