#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Feb 25, 2025 12:26:59 PM PST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
set vTcl(project_theme) winnative



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -relief groove -background SystemButtonFace \
        -highlightbackground SystemButtonFace \
        -highlightcolor SystemWindowText 
    wm focusmodel $top passive
    wm geometry $top 605x490+604+270
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ::vTcl::widgets::ttk::labelframe::createCmd "$top.tLa52" \
        -text "Output Directory" -width 240 -height 75 
    vTcl:DefineAlias "$top.tLa52" "LF_outputDir" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tLa52
    ttk::button "$site_3_0.tBu54" \
        -text "Open" -underline 0 -compound left 
    vTcl:DefineAlias "$site_3_0.tBu54" "B_outputDir" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu47" \
        -text "Default" -compound left 
    vTcl:DefineAlias "$site_3_0.tBu47" "B_outputDirDefault" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor e \
        -background SystemButtonFace -compound left \
        -disabledforeground #b4b4b4 \
        -font "-family {Segoe UI} -size 9 -slant italic" \
        -foreground SystemWindowText -highlightbackground SystemButtonFace \
        -highlightcolor SystemWindowText -justify right -padx 3 \
        -relief sunken -state disabled -text "Label" 
    vTcl:DefineAlias "$site_3_0.lab47" "L_outputDirPath" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tBu54 \
        -in $site_3_0 -x 184 -y 44 -width 45 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu47 \
        -in $site_3_0 -x 120 -y 44 -width 57 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 10 -y 20 -width 214 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    ::vTcl::widgets::ttk::labelframe::createCmd "$top.tLa47" \
        -text "Input Python Code" -width 240 -height 75 
    vTcl:DefineAlias "$top.tLa47" "LF_inputFile" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tLa47
    label "$site_3_0.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor e \
        -background SystemButtonFace -compound left \
        -disabledforeground #b4b4b4 -font "-family {Segoe UI} -size 9" \
        -foreground SystemWindowText -highlightbackground SystemButtonFace \
        -highlightcolor SystemWindowText -justify right -text "Label" 
    vTcl:DefineAlias "$site_3_0.lab49" "L_inputFileValid" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab48" \
        -activebackground #d9d9d9 -activeforeground black -anchor e \
        -background SystemButtonFace -compound left \
        -disabledforeground #b4b4b4 \
        -font "-family {Segoe UI} -size 9 -slant italic" \
        -foreground SystemWindowText -highlightbackground SystemButtonFace \
        -highlightcolor SystemWindowText -justify right -padx 3 \
        -relief sunken -state disabled -text "Label" 
    vTcl:DefineAlias "$site_3_0.lab48" "L_inputFilePath" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu49" \
        -text "Open" -underline 0 -compound left 
    vTcl:DefineAlias "$site_3_0.tBu49" "B_inputFile" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab49 \
        -in $site_3_0 -x 10 -y 50 -width 0 -relwidth 0.892 -height 0 \
        -relheight 0.28 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.267 -width 0 \
        -relwidth 0.683 -height 0 -relheight 0.293 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu49 \
        -in $site_3_0 -x 0 -relx 0.767 -y 0 -rely 0.227 -width 45 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    ::vTcl::widgets::ttk::labelframe::createCmd "$top.tLa51" \
        -text "Renaming Parameters" -relief groove -width 300 -height 155 
    vTcl:DefineAlias "$top.tLa51" "LF_renameParams" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tLa51
    vTcl::widgets::ttk::custom::CreateCmd "$site_3_0.cus57" \
        -background SystemButtonFace -height 75 \
        -highlightbackground SystemButtonFace \
        -highlightcolor SystemWindowText -width 125 
    vTcl:DefineAlias "$site_3_0.cus57" "Custom1" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab54" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background SystemButtonFace -compound left \
        -disabledforeground #b4b4b4 -font "-family {Segoe UI} -size 9" \
        -foreground SystemWindowText -highlightbackground SystemButtonFace \
        -highlightcolor SystemWindowText -text "Translation Languages" 
    vTcl:DefineAlias "$site_3_0.lab54" "L_translateLangs" vTcl:WidgetProc "Toplevel1" 1
    ::vTcl::widgets::ttk::labelframe::createCmd "$site_3_0.tLa53" \
        -text "Probabilities" -width 120 -height 125 
    vTcl:DefineAlias "$site_3_0.tLa53" "LF_renameProbs" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.tLa53
    label "$site_4_0.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background SystemButtonFace -compound left \
        -disabledforeground #b4b4b4 -font "-family {Segoe UI} -size 9" \
        -foreground SystemWindowText -highlightcolor SystemWindowText \
        -text "Variables:" 
    vTcl:DefineAlias "$site_4_0.lab51" "L_renameVarProb" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background SystemButtonFace -compound left \
        -disabledforeground #b4b4b4 -font "-family {Segoe UI} -size 9" \
        -foreground SystemWindowText -highlightcolor SystemWindowText \
        -text "Functions:" 
    vTcl:DefineAlias "$site_4_0.lab50" "L_renameFuncProb" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab55" \
        -activebackground #d9d9d9 -activeforeground black -anchor e \
        -background SystemButtonFace -compound left \
        -disabledforeground #b4b4b4 -font "-family {Segoe UI} -size 9" \
        -foreground SystemWindowText -highlightbackground SystemButtonFace \
        -highlightcolor SystemWindowText -justify right -text "Label" 
    vTcl:DefineAlias "$site_4_0.lab55" "L_renameFuncProbRange" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor e \
        -background SystemButtonFace -compound left \
        -disabledforeground #b4b4b4 -font "-family {Segoe UI} -size 9" \
        -foreground SystemWindowText -highlightbackground SystemButtonFace \
        -highlightcolor SystemWindowText -justify right -text "Label" 
    vTcl:DefineAlias "$site_4_0.lab56" "L_renameVarProbRange" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_0.ent53" \
        -background white -disabledforeground #b4b4b4 \
        -font "-family {Courier New} -size 10" -foreground SystemWindowText \
        -highlightbackground SystemButtonFace \
        -highlightcolor SystemWindowText -insertbackground SystemWindowText \
        -selectbackground #d9d9d9 -selectforeground black -width 44 
    vTcl:DefineAlias "$site_4_0.ent53" "E_renameVarProb" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_0.ent52" \
        -background white -disabledforeground #b4b4b4 \
        -font "-family {Courier New} -size 10" -foreground SystemWindowText \
        -highlightbackground SystemButtonFace \
        -highlightcolor SystemWindowText -insertbackground SystemWindowText \
        -selectbackground #d9d9d9 -selectforeground black -width 44 
    vTcl:DefineAlias "$site_4_0.ent52" "E_renameFuncProb" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background SystemButtonFace -compound left \
        -disabledforeground #b4b4b4 -font "-family {Segoe UI} -size 9" \
        -foreground SystemWindowText -highlightbackground SystemButtonFace \
        -highlightcolor SystemWindowText -text "%" 
    vTcl:DefineAlias "$site_4_0.lab52" "L_renameFuncProbPercent" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background SystemButtonFace -compound left \
        -disabledforeground #b4b4b4 -font "-family {Segoe UI} -size 9" \
        -foreground SystemWindowText -highlightbackground SystemButtonFace \
        -highlightcolor SystemWindowText -text "%" 
    vTcl:DefineAlias "$site_4_0.lab53" "L_renameVarProbPercent" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab51 \
        -in $site_4_0 -x 4 -y 70 -width 64 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab50 \
        -in $site_4_0 -x 4 -y 20 -width 74 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab55 \
        -in $site_4_0 -x 6 -y 44 -width 44 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab56 \
        -in $site_4_0 -x 6 -y 94 -width 44 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent53 \
        -in $site_4_0 -x 54 -y 94 -width 44 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent52 \
        -in $site_4_0 -x 54 -y 44 -width 44 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab52 \
        -in $site_4_0 -x 98 -y 44 -width 14 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab53 \
        -in $site_4_0 -x 98 -y 94 -width 14 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.cus57 \
        -in $site_3_0 -x 140 -y 28 -width 144 -relwidth 0 -height 117 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 140 -y 10 -width 144 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa53 \
        -in $site_3_0 -x 10 -y 20 -width 120 -relwidth 0 -height 125 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tLa52 \
        -in $top -x 20 -y 90 -width 240 -relwidth 0 -height 75 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa47 \
        -in $top -x 20 -y 10 -width 240 -relwidth 0 -height 75 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa51 \
        -in $top -x 280 -y 10 -width 300 -relwidth 0 -height 155 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

