#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Feb 25, 2025 08:14:27 PM PST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import ArgosTranslate_PreReqs_Installer_support

_bgcolor = "#d9d9d9"
_fgcolor = "#000000"
_tabfg1 = "black"
_tabfg2 = "white"
_bgmode = "light"
_tabbg1 = "#d9d9d9"
_tabbg2 = "gray40"


class Toplevel1:
    def __init__(self, top=None):
        """This class configures and populates the toplevel window.
        top is the toplevel containing window."""

        top.geometry("438x450+702+270")
        top.minsize(438, 450)
        top.maxsize(1920, 1060)
        top.resizable(1, 1)
        top.title("ArgosTranslate Languages Installer")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top
        self.langs_installcount_str = tk.StringVar()

        self.F_langs = tk.Frame(self.top)
        self.F_langs.place(relx=0.023, rely=0.022, relheight=0.96, relwidth=0.959)
        self.F_langs.configure(relief="groove")
        self.F_langs.configure(borderwidth="2")
        self.F_langs.configure(relief="groove")
        self.F_langs.configure(background="#d9d9d9")
        self.F_langs.configure(highlightbackground="#d9d9d9")
        self.F_langs.configure(highlightcolor="#000000")

        self.Label1 = tk.Label(self.F_langs)
        self.Label1.place(relx=0.024, rely=0.023, height=51, width=174)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor="nw")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound="left")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(justify="left")
        self.Label1.configure(text="""Install ArgosTranslate Language Packages""")
        self.Label1.configure(wraplength="174")

        self.L_langsList = tk.Label(self.F_langs)
        self.L_langsList.place(relx=0.483, rely=0.023, height=21, width=167)
        self.L_langsList.configure(activebackground="#d9d9d9")
        self.L_langsList.configure(activeforeground="black")
        self.L_langsList.configure(anchor="w")
        self.L_langsList.configure(background="#d9d9d9")
        self.L_langsList.configure(compound="left")
        self.L_langsList.configure(disabledforeground="#a3a3a3")
        self.L_langsList.configure(font="-family {Segoe UI} -size 12")
        self.L_langsList.configure(foreground="#000000")
        self.L_langsList.configure(highlightbackground="#d9d9d9")
        self.L_langsList.configure(highlightcolor="#000000")
        self.L_langsList.configure(text="""Available Languages:""")

        self.L_installerDesc2 = tk.Label(self.F_langs)
        self.L_installerDesc2.place(relx=0.048, rely=0.326, height=132, width=177)
        self.L_installerDesc2.configure(activebackground="#d9d9d9")
        self.L_installerDesc2.configure(activeforeground="black")
        self.L_installerDesc2.configure(anchor="nw")
        self.L_installerDesc2.configure(background="#d9d9d9")
        self.L_installerDesc2.configure(compound="left")
        self.L_installerDesc2.configure(disabledforeground="#a3a3a3")
        self.L_installerDesc2.configure(font="-family {Segoe UI} -size 9")
        self.L_installerDesc2.configure(foreground="#000000")
        self.L_installerDesc2.configure(highlightbackground="#d9d9d9")
        self.L_installerDesc2.configure(highlightcolor="#000000")
        self.L_installerDesc2.configure(justify="left")
        self.L_installerDesc2.configure(
            text="""For a given language X, it is displayed on the right as X <-> English. If selected, the X->English and English->X language packages are installed and can be used for random translation in the Python Obfuscator."""
        )
        self.L_installerDesc2.configure(wraplength="170")

        self.B_install = tk.Button(self.F_langs)
        self.B_install.place(relx=0.071, rely=0.789, height=66, width=137)
        self.B_install.configure(activebackground="#d9d9d9")
        self.B_install.configure(activeforeground="black")
        self.B_install.configure(background="#d9d9d9")
        self.B_install.configure(disabledforeground="#a3a3a3")
        self.B_install.configure(font="-family {Segoe UI} -size 16")
        self.B_install.configure(foreground="#000000")
        self.B_install.configure(highlightbackground="#d9d9d9")
        self.B_install.configure(highlightcolor="#000000")
        self.B_install.configure(text="""Install""")
        self.B_install.configure(
            command=ArgosTranslate_PreReqs_Installer_support.install_Langs
        )
        self.B_install.configure(state="disabled")

        self.B_deselectAll = tk.Button(self.F_langs)
        self.B_deselectAll.place(relx=0.5, rely=0.903, height=26, width=77)
        self.B_deselectAll.configure(activebackground="#d9d9d9")
        self.B_deselectAll.configure(activeforeground="black")
        self.B_deselectAll.configure(background="#d9d9d9")
        self.B_deselectAll.configure(disabledforeground="#a3a3a3")
        self.B_deselectAll.configure(font="-family {Segoe UI} -size 10")
        self.B_deselectAll.configure(foreground="#000000")
        self.B_deselectAll.configure(highlightbackground="#d9d9d9")
        self.B_deselectAll.configure(highlightcolor="#000000")
        self.B_deselectAll.configure(text="""Deselect All""")
        self.B_deselectAll.configure(
            command=ArgosTranslate_PreReqs_Installer_support.clearAll
        )

        self.B_selectAll = tk.Button(self.F_langs)
        self.B_selectAll.place(relx=0.738, rely=0.903, height=26, width=77)
        self.B_selectAll.configure(activebackground="#d9d9d9")
        self.B_selectAll.configure(activeforeground="black")
        self.B_selectAll.configure(background="#d9d9d9")
        self.B_selectAll.configure(disabledforeground="#a3a3a3")
        self.B_selectAll.configure(font="-family {Segoe UI} -size 10")
        self.B_selectAll.configure(foreground="#000000")
        self.B_selectAll.configure(highlightbackground="#d9d9d9")
        self.B_selectAll.configure(highlightcolor="#000000")
        self.B_selectAll.configure(text="""Select All""")
        self.B_selectAll.configure(
            command=ArgosTranslate_PreReqs_Installer_support.selectAll
        )

        self.L_installerDesc1 = tk.Label(self.F_langs)
        self.L_installerDesc1.place(relx=0.048, rely=0.139, height=82, width=177)

        self.L_installerDesc1.configure(activebackground="#d9d9d9")
        self.L_installerDesc1.configure(activeforeground="black")
        self.L_installerDesc1.configure(anchor="nw")
        self.L_installerDesc1.configure(background="#d9d9d9")
        self.L_installerDesc1.configure(compound="left")
        self.L_installerDesc1.configure(disabledforeground="#a3a3a3")
        self.L_installerDesc1.configure(font="-family {Segoe UI} -size 9")
        self.L_installerDesc1.configure(foreground="#000000")
        self.L_installerDesc1.configure(highlightbackground="#d9d9d9")
        self.L_installerDesc1.configure(highlightcolor="#000000")
        self.L_installerDesc1.configure(justify="left")
        self.L_installerDesc1.configure(
            text="""This program detects the available Argos Translate offline language packages and displays them for auto installation."""
        )
        self.L_installerDesc1.configure(wraplength="170")

        self.F_checklist = tk.Frame(self.F_langs)
        self.F_checklist.place(relx=0.476, rely=0.088, relheight=0.799, relwidth=0.464)
        self.F_checklist.configure(relief="groove")
        self.F_checklist.configure(borderwidth="2")
        self.F_checklist.configure(relief="groove")
        self.F_checklist.configure(background="#d9d9d9")
        self.F_checklist.configure(highlightbackground="#d9d9d9")
        self.F_checklist.configure(highlightcolor="#000000")

        self.C_scrolledChecklist = ArgosTranslate_PreReqs_Installer_support.Custom(
            self.F_checklist
        )
        self.C_scrolledChecklist.place(
            relx=0.0, rely=0.0, relheight=1.012, relwidth=0.995
        )

        self.L_langsInstallCount = tk.Label(self.F_langs)
        self.L_langsInstallCount.place(relx=0.071, rely=0.718, height=21, width=154)
        self.L_langsInstallCount.configure(activebackground="#d9d9d9")
        self.L_langsInstallCount.configure(activeforeground="black")
        self.L_langsInstallCount.configure(anchor="nw")
        self.L_langsInstallCount.configure(background="#d9d9d9")
        self.L_langsInstallCount.configure(compound="left")
        self.L_langsInstallCount.configure(disabledforeground="#a3a3a3")
        self.L_langsInstallCount.configure(font="-family {Segoe UI} -size 9")
        self.L_langsInstallCount.configure(foreground="#000000")
        self.L_langsInstallCount.configure(highlightbackground="#d9d9d9")
        self.L_langsInstallCount.configure(highlightcolor="#000000")
        self.L_langsInstallCount.configure(justify="left")
        self.L_langsInstallCount.configure(text="""Languages to Install: 0""")

        self.F_install = tk.Frame(self.top)
        self.F_install.place(relx=0.023, rely=0.022, relheight=0.96, relwidth=0.959)
        self.F_install.configure(relief="groove")
        self.F_install.configure(borderwidth="2")
        self.F_install.configure(relief="groove")
        self.F_install.configure(background="#d9d9d9")
        self.F_install.configure(highlightbackground="#d9d9d9")
        self.F_install.configure(highlightcolor="#000000")

        self.L_installTitle = tk.Label(self.F_install)
        self.L_installTitle.place(relx=0.024, rely=0.014, height=21, width=134)
        self.L_installTitle.configure(activebackground="#d9d9d9")
        self.L_installTitle.configure(activeforeground="black")
        self.L_installTitle.configure(anchor="w")
        self.L_installTitle.configure(background="#d9d9d9")
        self.L_installTitle.configure(compound="left")
        self.L_installTitle.configure(disabledforeground="#a3a3a3")
        self.L_installTitle.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.L_installTitle.configure(foreground="#000000")
        self.L_installTitle.configure(highlightbackground="#d9d9d9")
        self.L_installTitle.configure(highlightcolor="#000000")
        self.L_installTitle.configure(text="""Installing Languages""")

        self.L_installStatus = tk.Label(self.F_install)
        self.L_installStatus.place(relx=0.357, rely=0.88, height=31, width=254)
        self.L_installStatus.configure(activebackground="#d9d9d9")
        self.L_installStatus.configure(activeforeground="black")
        self.L_installStatus.configure(anchor="e")
        self.L_installStatus.configure(background="#d9d9d9")
        self.L_installStatus.configure(compound="left")
        self.L_installStatus.configure(disabledforeground="#a3a3a3")
        self.L_installStatus.configure(font="-family {Segoe UI} -size 12 -slant italic")
        self.L_installStatus.configure(foreground="#000000")
        self.L_installStatus.configure(highlightbackground="#d9d9d9")
        self.L_installStatus.configure(highlightcolor="#000000")
        self.L_installStatus.configure(text="""Installing...""")

        self.F_outputText = tk.Frame(self.F_install)
        self.F_outputText.place(relx=0.043, rely=0.093, relheight=0.729, relwidth=0.917)
        self.F_outputText.configure(relief="groove")
        self.F_outputText.configure(borderwidth="2")
        self.F_outputText.configure(relief="groove")
        self.F_outputText.configure(background="#d9d9d9")
        self.F_outputText.configure(highlightbackground="#d9d9d9")
        self.F_outputText.configure(highlightcolor="#000000")

        self.C_outputTextScrolled = ArgosTranslate_PreReqs_Installer_support.Custom2(
            self.F_outputText
        )
        self.C_outputTextScrolled.place(
            relx=0.0, rely=0.0, relheight=1.013, relwidth=0.997
        )
        self.C_outputTextScrolled.configure(wrap="word")
        self.C_outputTextScrolled.configure(state="disabled")

        self.F_langs.tkraise()


def start_up():
    ArgosTranslate_PreReqs_Installer_support.main()


if __name__ == "__main__":
    ArgosTranslate_PreReqs_Installer_support.main()
