# abbreviations list created based on common code abbreviations: https://github.com/abbrcode/abbreviations-in-code
abbreviations={'abbr': 'abbreviation', 'abs': 'absolute', 'acro': 'acronym', 'act': 'actual',
 'sum': 'addition', 'addr': 'address', 'algo': 'algorithm', 'alloc': 'allocation',
 'alt': 'alternative', 'anno': 'annotation', 'app': 'application',
 'acosec': 'arccosecant', 'acos': 'arccosine', 'acot': 'arccotangent',
 'actg': 'arccotangent', 'asec': 'arcsecant', 'asin': 'arcsine', 'atan': 'arctangent',
 'arg': 'argument', 'arr': 'array', 'async': 'asynchronous', 'attr': 'attribute',
 'auth': 'authentication', 'aux': 'auxiliary', 'avg': 'average', 'bg': 'background',
 'bat': 'battery', 'bin': 'binary', 'bool': 'boolean', 'brk': 'break', 'bl': 'breakline',
 'buf': 'buffer', 'buff': 'buffer', 'btn': 'button', 'calc': 'calculator',
 'cb': 'callback', 'cert': 'certificate', 'ch': 'channel', 'char': 'character',
 'chk': 'check', 'csum': 'checksum', 'circ': 'circle', 'cls': 'class', 'clr': 'clear',
 'coll': 'collection', 'col': 'column', 'cmd': 'command', 'com': 'communication',
 'comm': 'common', 'cmp': 'comparison', 'comp': 'component', 'concat': 'concatenation',
 'cond': 'condition', 'cfg': 'configuration', 'conf': 'configuration',
 'config': 'configuration', 'con': 'connection', 'conn': 'connection', 'const': 'constant',
 'cntr': 'container', 'ctx': 'context', 'cont': 'continue', 'ctrl': 'control',
 'conv': 'conversation', 'coord': 'coordinate', 'cpy': 'copy', 'cosec': 'cosecant',
 'cos': 'cosine', 'cot': 'cotangent', 'ctg': 'cotangent', 'cnt': 'count', 'cur': 'current',
 'curr': 'current', 'db': 'database', 'dbg': 'debug', 'dec': 'decrease',
 'decl': 'declaration', 'def': 'definition', 'deg': 'degrees', 'del': 'deletion',
 'dt': 'delta time', 'dep': 'dependency', 'desc': 'description', 'dest': 'destination',
 'dev': 'device', 'diff': 'difference', 'dim': 'dimension', 'dir': 'directory',
 'dis': 'disable', 'disp': 'display', 'div': 'division', 'doc': 'document',
 'docs': 'documentation', 'drv': 'driver', 'dyn': 'dynamic', 'elm': 'element',
 'en': 'enable', 'env': 'environment', 'eq': 'equal', 'err': 'error', 'evt': 'event',
 'exe': 'execution', 'exp': 'exponential', 'expr': 'expression', 'ext': 'extension',
 'fct': 'facet', 'fac': 'factory', 'fig': 'figure', 'fc': 'file chooser',
 'fd': 'file descriptor', 'fp': 'function pointer', 'fr': 'file reader',
 'fs': 'file system', 'fw': 'file writer', 'e.g.': 'for example', 'fmt': 'format',
 'frac': 'fraction', 'freq': 'frequence', 'fn': 'function', 'func': 'function',
 'gen': 'generation', 'geom': 'geometry', 'ge': 'greater or equal',
 'gt': 'greater than', 'hw': 'hardware', 'hdr': 'header', 'hex': 'hexadecimal',
 'hor': 'horizontal', 'id': 'identifier', 'img': 'image', 'impl': 'implementation',
 'imp': 'import', 'inc': 'increase', 'idx': 'index', 'info': 'information',
 'init': 'initialization', 'in': 'input', 'ins': 'insertion', 'inst': 'instance',
 'int': 'integer', 'iface': 'interface', 'intf': 'interface', 'inv': 'inverse',
 'iter': 'iterator', 'km': 'keymap', 'kwd': 'keyword', 'lang': 'language',
 'lat': 'latitude', 'len': 'length', 'le': 'less or equal', 'lt': 'less than',
 'lvl': 'level', 'lib': 'library', 'lnk': 'link', 'll': 'linked list', 'loc': 'location',
 'lon': 'longitude', 'mng': 'manager', 'mat': 'matrix', 'mtx': 'matrix', 'max': 'maximum',
 'mem': 'memory', 'msg': 'message', 'meta': 'metadata', 'mcu': 'microcontroller',
 'mid': 'middle', 'min': 'minimum', 'misc': 'miscellaneous', 'mod': 'modulo',
 'mul': 'multiplication', 'mut': 'mutable', 'nav': 'navigation', 'net': 'network',
 'nl': 'newline', '$...': 'node', 'ne': 'not equal', 'num': 'number of', 'obj': 'object',
 'key': 'object key', 'oct': 'octal', 'os': 'operating system', 'oss': 'open source software',
 'op': 'operation', 'opt': 'option', 'ord': 'order', 'org': 'organization', 'orig': 'origin',
 'out': 'output', 'pkg': 'package', 'param': 'parameter', 'perf': 'performance',
 'pic': 'picture', 'px': 'pixel', 'ptr': 'pointer', 'pol': 'poligon', 'pos': 'position',
 'pwr': 'power', 'pred': 'prediction', 'pref': 'preference', 'prev': 'previous',
 'priv': 'private', 'proc': 'process', 'prod': 'production', 'prof': 'profiler',
 'pub': 'public', 'qry': 'query', 'rad': 'radians', 'rand': 'random', 'rnd': 'random',
 'rng': 'range', 'recv': 'receive', 'rec': 'record', 'rect': 'rectangle', 'ref': 'reference',
 'regex': 'regular expression', 'rgx': 'regular expression', 'rel': 'relation',
 'rem': 'remote', 'rm': 'remove', 'rmv': 'remove', 'repo': 'repository', 'req': 'request',
 'res': 'result', 'ret': 'return', 'rev': 'revision', 'sc': 'script', 'sec': 'secant',
 'sel': 'selection', 'sem': 'semaphore', 'sep': 'separator', 'seq': 'sequence', 'svc': 'service',
 'sess': 'session', 'sin': 'sine', 'sw': 'software', 'sln': 'solution', 'sol': 'solver',
 'src': 'source', 'spec': 'specification', 'sqrt': 'square root', 'std': 'standard',
 'stdio': 'standard input output', 'stmt': 'statement', 'stat': 'statistic', 'str': 'string',
 'sub': 'subtration', 'sync': 'synchronization', 'td': 'table data', 'th': 'table header', 'tr':
 'table row', 'tan': 'tangent', 'tgt': 'target', 'tmp': 'temporary', 'temp': 'temporary', 'txt':
 'text', 'tmr': 'timer', 'ts': 'timestamp', 'tgl': 'toggle', 'tx': 'transaction', 'tpe': 'type',
 'usr': 'user', 'util': 'utility', 'val': 'value', 'var': 'variable', 'vec': 'vector', 'ver':
 'vertical', 'ws': 'white space', 'win': 'window', 'wiz': 'wizard'}